spring.application.name=liga
# Konfiguracja bazy H2 w pamięci
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:ligadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Włączenie generowania tabel na podstawie encji
spring.jpa.hibernate.ddl-auto=update
# Wyświetlanie zapytań SQL w konsoli (przydatne do debugowania)
spring.jpa.show-sql=true
